server:
  port: 8080

1466951331:
  swagger-open: true              #æ˜¯å¦å¼€å¯swagger (true/false)
  kaptcha-open: false             #æ˜¯å¦å¼€å¯ç™»å½•æ—¶éªŒè¯ç ?(true/false)
  #  file-upload-path: d:/tmp     #æ–‡ä»¶ä¸Šä¼ ç›®å½•(ä¸é…ç½®çš„è¯ä¸ºjava.io.tmpdirç›®å½•)
  spring-session-open: false      #æ˜¯å¦å¼€å¯spring session,å¦‚æœæ˜¯å¤šæœºç¯å¢ƒéœ€è¦å¼€å?true/false)
  session-invalidate-time: 1800     #sessionå¤±æ•ˆæ—¶é—´(åªåœ¨å•æœºç¯å¢ƒä¸‹ç”Ÿæ•ˆï¼Œå¤šæœºç¯å¢ƒåœ¨SpringSessionConfigç±»ä¸­é…ç½®) å•ä½ï¼šç§’
  session-validation-interval: 900  #å¤šä¹…æ£€æµ‹ä¸€æ¬¡å¤±æ•ˆçš„session(åªåœ¨å•æœºç¯å¢ƒä¸‹ç”Ÿæ•? å•ä½ï¼šç§’

beetl:
  resource-auto-check: true       #çƒ­åŠ è½½beetlæ¨¡æ¿ï¼Œå¼€å‘æ—¶å€™ç”¨

spring:
  profiles:
    active: @spring.active@
  mvc:
    static-path-pattern: /static/**
    view:
      prefix: /WEB-INF/view
  devtools:
    restart:
      enabled: false
      additional-paths: src/main/java
      exclude: static/**,WEB-INF/view/**
  servlet:
    multipart:
      max-request-size: 100MB
      max-file-size: 100MB

mybatis-plus:
  typeAliasesPackage: cn.stylefeng.1466951331.modular.system.model

log:
  path: 1466951331-logs

---

spring:
  profiles: local
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/1466951331?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=CTT
    username: root
    password: 123456
    filters: wall,mergeStat

#å¤šæ•°æ®æºæƒ…å†µçš„é…ç½?
1466951331:
  muti-datasource:
    open: false
    url: jdbc:mysql://127.0.0.1:3306/1466951331_test?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=CTT
    username: root
    password: 123456
    dataSourceNames:
    - dataSource1466951331
    - dataSourceBiz

---

spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/1466951331?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=CTT
    username: root
    password: 123456
    filters: wall,mergeStat

---

spring:
  profiles: test
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/1466951331?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=CTT
    username: root
    password: 123456
    filters: wall,mergeStat

---

spring:
  profiles: produce
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/1466951331?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=CTT
    username: root
    password: 123456
    filters: wall,mergeStat

